services:
  db:
    image: postgis/postgis:16-3.4
    container_name: implantation_postgis
    environment:
      POSTGRES_DB: implantation
      POSTGRES_USER: implantation_user
      POSTGRES_PASSWORD: implantation_password
    ports:
      - "5433:5432"
    volumes:
      - implantation_pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  implantation_pgdata:
